//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 07:21:45 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3school.com.cn")
package com.market.marketbarn.model;
