//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 07:21:45 PM CST 
//


package com.market.marketbarn.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="syncPolicy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="syncDuration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="syncInterval" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "syncPolicy",
    "syncDuration",
    "syncInterval"
})
@XmlRootElement(name = "SyncConfig")
public class SyncConfig {

    @XmlElement(required = true)
    protected String syncPolicy;
    @XmlElement(required = true)
    protected String syncDuration;
    @XmlElement(required = true)
    protected BigInteger syncInterval;

    /**
     * Gets the value of the syncPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncPolicy() {
        return syncPolicy;
    }

    /**
     * Sets the value of the syncPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncPolicy(String value) {
        this.syncPolicy = value;
    }

    /**
     * Gets the value of the syncDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncDuration() {
        return syncDuration;
    }

    /**
     * Sets the value of the syncDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncDuration(String value) {
        this.syncDuration = value;
    }

    /**
     * Gets the value of the syncInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSyncInterval() {
        return syncInterval;
    }

    /**
     * Sets the value of the syncInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSyncInterval(BigInteger value) {
        this.syncInterval = value;
    }

}
